spring:
  application:
    name: ape-sharging-sphere
#========================基本配置
  shardingsphere:
    mode:
      type: Memory  # 内存模式 可选配置：Memory、Standalone、Cluster
    props:
      sql-show: true # 是否打印sql
      sql-simple: true # 打印简单的sql

#========================数据源配置
    datasource:
      names: master,slave1,slave2
      master: # 数据源名称
        type: com.alibaba.druid.pool.DruidDataSource  # 数据源完整类名
        driver-class-name: com.mysql.cj.jdbc.Driver  # 数据库驱动类名，以数据库连接池自身配置为准
        url: jdbc:mysql://192.168.1.132:3306/db_test?serverTimeZone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.132:3307/db_test?serverTimeZone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
      slave2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.132:3308/db_test?serverTimeZone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
#========================配置读写分离规则
    rules:
      readwrite-splitting:
        data-sources:
          myds:
            type: Static  # 读写分离类型，如: Static，Dynamic
            props:
              auto-aware-data-source-name: master
              write-data-source-name: master
              read-data-source-names: slave1,slave2
            load-balancer-name: alg_round
        load-balancers:
          alg_round:
            type: ROUND_ROBIN # 轮询算法
          alg_random:
            type: RANDOM  # 随机访问算法
          alg_weight:
            type: WEIGHT  # 权重访问算法(double)
            props:
              slave1: 1.0
              slave2: 2.0
