server:
  port: 8080

spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ape-frame?serverTimeZone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20  #最小空闲
      max-active: 100
      max-wait: 60000
      # StatViewServlet配置。（因为暴露的监控信息比较敏感，支持密码加密和访问ip限定）
      #对配置已开启的 filters 即 stat(sql 监控)wall（防火墙）
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: true
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-idle: 8   # 空闲连接数
        max-wait: -1
        min-idle: 0



mybatis-plus:
#  mapper-locations: classpath*:mapper/**.xml
  # 逻辑删除
  global-config:
    db-config:
      logic-delete-field: delete_flag
      logic-delete-value: 1
      logic-not-delete-value: 0
swagger:
  base-package: com.paopao.user
  title: ape-frame
  contact-name: 我是paopao
  contact-url: 地址
  email: paopao@163.com
  version: 1.0
  description: 从0到1 开箱即用脚手架


sql:
  beauty:
    show: true

