server:
  port: 9100
spring:
  application:
    name: cda-service
  datasource:
    dynamic:
      primary: DICTITEM #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      druid: #以下是全局默认值，可以全局更改
        # 初始化大小，最小，最大
        initial-size: 20
        min-idle: 20
        max-active: 80
        # 配置获取连接等待超时的时间
        max-wait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 300000
      datasource:
        # 文书库
        CDAVIEW:
          url: jdbc:mysql://10.195.56.15:3390/JHVIEW?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&rewriteBatchedStatements=true&tinyInt1isBit=false&allowMultiQueries=true&sessionVariables=group_concat_max_len=1024000
          username: root
          password: jhmk5354(#($
          driver-class-name: com.mysql.cj.jdbc.Driver
        # Oracle主库
        DICTITEM:
          url: jdbc:oracle:thin:@10.195.57.26:1521/orcl1
          username: jhdcp
          password: jhmk123456
          driver-class-name: oracle.jdbc.OracleDriver

